### ISSUE TITLE
schema-inspector is missing

### ISSUE THREAD

**Issue by Nonemoticoner** [ebdrup/json-schema-benchmark#22]
I believe this one should be benchmarked as well. 

[schema-inspector](https://github.com/Atinux/schema-inspector)

**Comment by ebdrup** [comment]
PRs wellcome :-)

**Comment by Nonemoticoner** [comment]
@ebdrup I will see to that ;)

**Comment by ebdrup** [comment]
awesome :+1:

**Comment by ebdrup** [comment]
hmm, it looks like they are not implementing the official JSON-schema standard, but have come up with their own schema standard. As such it would not make sense to add it to this benchmark. This benchmark is only for implementations of the official JSON-schema standard.
