### ISSUE TITLE
Clarify mechanism to update benchmark results

### ISSUE THREAD

**Issue by Prestaul** [ebdrup/json-schema-benchmark#29]
I just realized there were updates to the test suite and released v1.2.4 of skeemas which fixes about 11 of the test failures currently reported.

I'm happy to submit PRs to help update benchmark results but I understand the benchmark owners would prefer to run them independently. What is the correct mechanism for library owners to request an update of these results?

**Comment by epoberezkin** [comment]
I can re-run and push.
