### ISSUE TITLE
Make it clear what parts of the spec a JSON-schema validator deliberately chose not to implement

### ISSUE THREAD

**Issue by gilesbowkett** [ebdrup/json-schema-benchmark#4]
discussion started in JSCK repo (https://github.com/pandastrike/jsck/pull/78) but belongs here.

JSCK passes all the JSON Schema Test Suite tests, [except for a few features we've elected not to support](https://github.com/pandastrike/jsck/blob/master/test/draft4/official.coffee). but with more insight into these tests, we might want to support them also.

**Comment by Muscula** [comment]
I tried not to derail the discussion on the jsck issue - and obviously failded - sorry.
But I have actually already fixed this issue in the benchmarks yesterday. I relaxed the requirements to get into the benchmarks just for jsck. 

So passing the unique items tests is no longer required to get into the benchmarks - even though many of the other validators do actually implement the unique items correctly.

**Comment by gilesbowkett** [comment]
ok, but you said it threw this huge list of errors?

https://github.com/pandastrike/jsck/pull/78#issuecomment-71968297

**Comment by Muscula** [comment]
These are the tests currently failing for jsck 
https://github.com/Muscula/json-schema-benchmark/blob/master/reports/jsck.md

I think that corresponds to the tests you have chosen not to implement as far as I could see at a glance.

**Comment by gilesbowkett** [comment]
ok, since you know where those errors came from, please say so in the error report. (per above issue.)

**Comment by Muscula** [comment]
I'm not quite sure what you mean? The failing tests are remote refs and uniqueItems, that jsck does not support, right?
What is it that you want me to add to the error report?

**Comment by gilesbowkett** [comment]
something like "these tests fail because JSCK deliberately chose against supporting these features, and/or because (in the case of `zeroTerminatedFloats`) the tests are not relevant for any JavaScript implementation."

if you know that all of the failing tests are testing features that JSCK deliberately doesn't implement, it's nice to say so.

check out [the json-schema-tests repo](https://github.com/pandastrike/json-schema-tests). it's a test harness for running the official JSON Schema tests.

the test harness allows you to very explicitly specify, in code, exactly which features of the spec any given validator has elected not to support.

[there are examples for JSCK, is-my-json-valid, json-gate, and tv4](https://github.com/pandastrike/json-schema-tests/tree/master/examples).

you could adapt this code and use it.

apart from anything else, it's interesting to see which features are consistently not implemented; it's a kind of feedback, for the spec authors, on the perceived usefulness of those features.

**Comment by Muscula** [comment]
I can see how it would be useful to see parts of the spec that were deliberately chosen not to be supported, by a json-schema validator.

I was thinking that this could be something specified in the modules package.json. That way the module exposes it clearly in a machine readable format. And the module author only has to maintain this in package.json, if hes/she decides to support more/less of the specs.

This all depends on weather this is something that @mafintosh, @playlyfe, @zaggino, @acornejo, @Prestaul, @bugventure, @tdegrunt, @geraintluff, @iclanzan, and @natesilva could see themselves putting in their package.json.

**Comment by gilesbowkett** [comment]
well, OK, but see the previous comment.

the https://github.com/pandastrike/json-schema-tests/ mechanism already exists, is already machine-readable, and has already been implemented for several validators.

**Comment by acornejo** [comment]
personally I think the point of a schema validator is to at least try to comply with every aspect of a spec.

Think of html, and those browsers that only support a subset of it, or that they do not comply with the spec (I am looking at you ie), they clearly make life painful for others. If at all possible, I think its best to provide software that complies to standards they are advertised to support.

I wasn't aware of your benchmark, great work. I am surprised to see how many validators there are out there. I didn't know that jjv was failing some tests, when I get some time I will amend jjv to try to pass all of them. However, given how slow jjv seems to be compared to others (I find this very surprising btw), I am not sure if there is still interest on it (I already finished the project I needed jjv for, so in that sense I've taken jjv as far as I needed).

**Comment by gilesbowkett** [comment]
> I am surprised to see how many validators there are out there.

@acornejo I can tell you from experience that the best way to find the fastest JSON Schema validator on the whole internet is to write one which is faster than any other you know about, brag about it, and watch all the people who wrote something even faster show up.

srsly, I googled the hell out of this topic before writing my blog post, and that accomplished nothing compared to writing [my own blog post about how fast my company's project was](http://gilesbowkett.blogspot.com/2015/01/why-panda-strike-wrote-fastest-json.html). :-)

**Comment by acornejo** [comment]
@gilesbowkett I believe you. I did not set out to have the fastest json-schema validator.

Ironically, I do not enjoy coding very much (I do love solving problems however, even if it involves coding). At the time I wrote jjv I first searched for something packaged I could use, there were a few contenders, but they wouldn't work out-of-the-box. I looked at the source to try to see if i could patch them to make them work, but the code was messy and unreadable and so it seemed easier to build a very simple one from scratch. I was surprised when (at the time) it also turned out to be faster than the existing solutions.

I am glad this is not the case anymore, in particular because I don't use jjv anymore (its deployed and working well, no need to patch it for my own use), so its great that there are good substitutes out there for other folks (or even myself, if I ever need json validation again).

**Comment by Prestaul** [comment]
I love this conversation. Mine is the newest entrant to the group and I simply wrote it (two weeks ago) because I needed features that were not in the existing solutions and wanted a canvas upon which to develop those features. I was very surprised to see that mine was the most compliant of the options out there (supporting everything except for the zeroTerminatedFloats).

My two cents are that this benchmark is doing a clear job of documenting current compliance and performance. There will be those who care more about performance, those who care about compliance, and those who care about feature set. Only the first two can be documented here in an automated fashion and the third is really best up to individual authors to publicize.

**Comment by gilesbowkett** [comment]
Convincing everybody to add new stuff to their `package.json` looks like more work for them.

The `json-schema-tests` repo already has a very nice and robust system for capturing compliance variations in code, with [some of the work already done](https://github.com/pandastrike/json-schema-tests/tree/master/examples).

Rock on with this, by all means, but for myself, I'm more likely to extract the [more comprehensive](http://gilesbowkett.blogspot.com/2015/01/why-panda-strike-wrote-fastest-json.html#jsck-benchmarks) benchmarking [from JSCK](https://github.com/pandastrike/jsck/blob/master/doc/benchmarks.md) and combine it with the [more statistically robust](https://github.com/pandastrike/jsck/issues/81#issuecomment-72319685) approach from themis (TLDR: use `benchmark`).

**Comment by Muscula** [comment]
To me, the only way a benchmark is:
 
- Not going to turn into a maintenance nightmare
- Not grow stale with configuration not being updated. 
- Stay as objective as possible
- Stay true to what a user of a particular validator will experience, using it right out of the box.

Is if the benchmark can be run 100% automated. 

I've put some thoughts in [CONTRIBUTING.md](https://github.com/Muscula/json-schema-benchmark/blob/master/CONTRIBUTING.md)

As @Prestaul mentions, the featuresets can also not be captured automatically. For that information I link to the validator homepage ever single time a validator is mentioned. The same goes for choosing not to support parts of the spec. Unless this information can be captured in a way that does not require maintenance (Like looking it up in the validators package.json)

I'va added an issue for altering the way the benchmark is done a little https://github.com/Muscula/json-schema-benchmark/issues/11. Suggestions for improvements are welcome.

You should definitely keep doing your own benchmarks. I believe the benchmarks you yourself do, serve a very different purpose than the one here.
